language: r
r:
  - oldrel
  - release
  - devel

cache: packages

# environment variables set for all builds
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

services:
  - docker

script:
  - wget -O- http://build-in-debian.bzed.at/script.sh | sh -

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: change